# Nome da aplicação
spring.application.name=emailmq

# Configuração do RabbitMQ (Substitua com suas credenciais do CloudAMQP)
spring.rabbitmq.host=seu-host.rmq.cloudamqp.com
spring.rabbitmq.port=5672
spring.rabbitmq.username=seu-usuario
spring.rabbitmq.password=sua-senha
spring.rabbitmq.virtual-host=seu-virtual-host

# Configuração do Banco de Dados H2 e visualização do Console
spring.datasource.url=jdbc:h2:mem:emaildb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.show-sql=true
